-- ===========================================
-- ALUCANSA DASHBOARD - DATOS INICIALES
-- ===========================================
-- Ejecutar este script DESPUÉS de schema.sql
-- para insertar los datos de ejemplo

-- ===========================================
-- ÁREAS
-- ===========================================
INSERT INTO areas (id, codigo, nombre, descripcion, prioridad, is_custom) VALUES
('area1', 'ORG', 'Organización y modelo operativo', 'Estructura organizativa, definición de roles, gobierno del dato y forma en que las decisiones se apoyan (o no) en información fiable.', 'alto', 0),
('area2', 'ALM', 'Almacén y logística', 'Gestión de existencias, movimientos entre almacenes, preparación de pedidos y coordinación logística con producción y clientes.', 'alto', 0),
('area3', 'ADM', 'Administración, facturación y contabilidad', 'Procesos administrativos, facturación, contabilidad, conciliaciones y reporting financiero.', 'alto', 0),
('area4', 'VEN', 'Ventas, cliente y área comercial', 'Relación con clientes, gestión de oportunidades, pedidos comerciales y calidad de servicio percibida.', 'medio', 0),
('area5', 'PRO', 'Producción', 'Planificación, ejecución y control de la fabricación, con especial foco en extrusión y acabados.', 'alto', 0),
('area6', 'DIR', 'Dirección y estrategia', 'Enfoque estratégico, priorización de inversiones, gobierno de proyectos y cultura de mejora continua.', 'alto', 0);

-- ===========================================
-- PROBLEMAS - ÁREA 1: ORGANIZACIÓN
-- ===========================================
INSERT INTO problemas (id, area_id, titulo, descripcion, impacto, urgencia, causas, evidencias, solucion_propuesta, pasos_implementacion, coste_minimo, coste_maximo, roi_minimo, roi_maximo, roi_justificacion, dependencias, tags, is_custom) VALUES
('ORG-1', 'area1', 'Ausencia de responsable claro del dato y de procesos', 'No existe una figura formal que asuma la responsabilidad global sobre la calidad del dato, la coherencia de los procesos y la coordinación entre departamentos.', 'alto', 'corto', '["Crecimiento orgánico de la empresa sin rediseñar la estructura", "Responsabilidades históricas asumidas por personas y no por puestos", "Falta de gobierno del dato y de procesos documentado"]', '["Nadie puede explicar de principio a fin el flujo de un pedido con datos fiables", "Cada departamento tiene una visión parcial y a veces contradictoria de la realidad", "Las incidencias de datos se parchean pero no se atacan de raíz"]', 'Crear la figura de Responsable de Procesos y Datos (interno o compartido) con autoridad transversal para definir, documentar y velar por el cumplimiento de los procesos y estándares de información.', '["Definir funciones y alcance del rol (responsable del dato y procesos)", "Asignar la función a una persona interna o incorporar un perfil adecuado", "Documentar responsabilidades, indicadores clave y canales de comunicación", "Establecer un circuito de gestión de incidencias de datos y procesos", "Revisar trimestralmente avances y bloqueos con la Dirección"]', 3000, 8000, 150, 400, 'Ahorro estimado de 15-25h/semana en resolución de incidencias y duplicidades. Una persona con visión transversal evita retrabajos y errores que hoy cuestan ~€500-1.000/semana entre tiempo perdido, urgencias y decisiones mal informadas.', '[]', '["gobierno del dato", "procesos", "organización"]', 0),

('ORG-2', 'area1', 'Procesos no documentados y dependientes de personas clave', 'Los procesos críticos de negocio están en la cabeza de unas pocas personas y no existen procedimientos escritos, versiones oficiales ni circuitos estándar.', 'alto', 'medio', '["Falta de tiempo y metodología para documentar procedimientos", "Cultura de \\"cada uno sabe lo suyo\\"", "Ausencia de plantillas y responsables de documentación"]', '["Discrepancias entre sedes sobre cómo se hacen tareas iguales", "Dificultad para sustituir a personas clave cuando no están presentes", "Cambios de criterio frecuentes sin trazabilidad ni comunicación formal"]', 'Implantar un sistema ligero de documentación de procesos (procedimientos operativos estándar) accesible para toda la organización.', '["Seleccionar una herramienta simple para documentación (Wiki interna, Notion, Confluence o similar)", "Priorizar los procesos críticos que deben documentarse primero", "Asignar responsables de redacción y validación por proceso", "Definir formato estándar de procedimiento (objetivo, pasos, responsables, entradas/salidas)", "Implantar un ciclo de revisión anual de procesos"]', 2000, 5000, 100, 300, 'Reducción del tiempo de formación de nuevos empleados (~40%), menor dependencia de personas clave (riesgo valorado en ~€15.000/año) y eliminación de errores por desconocimiento de procedimientos (~5h/semana).', '["ORG-1"]', '["procedimientos", "documentación", "conocimiento"]', 0),

('ORG-3', 'area1', 'Decisiones reactivas sin indicadores comunes', 'La empresa toma decisiones importantes sobre precios, stocks, producción y personal sin un cuadro de indicadores compartido ni criterios homogéneos.', 'alto', 'medio', '["No existe un cuadro de mando mínimo consensuado", "Cada área calcula \\"sus números\\" con herramientas distintas", "Falta de cultura de dato como base de decisión"]', '["Discurso recurrente de \\"no tenemos datos fiables\\"", "Dificultad para responder preguntas básicas sobre rentabilidad por línea o por cliente", "Discusión frecuente sobre qué cifras son las \\"buenas\\""]', 'Definir un cuadro de mando básico transversal con indicadores mínimos por área, alimentado con datos reales, aunque al principio la extracción no sea perfecta.', '["Definir junto a Dirección el set mínimo de KPIs (ventas, margen, servicio, desperdicio, incidencias, etc.)", "Identificar de dónde sale cada dato y quién es responsable", "Montar un primer cuadro de mando simple (Excel avanzado, Power BI u otra herramienta BI)", "Revisar mensualmente los indicadores con los responsables de área", "Ajustar definición y fuentes de datos según se detecten incoherencias"]', 3000, 8000, 120, 350, 'Mejora en la toma de decisiones que puede evitar ~2-3% de pérdidas por malas decisiones de precio, stock o producción. En una facturación de 3-5M€ representa €60.000-150.000/año de impacto potencial.', '["ORG-1"]', '["kpi", "cuadro de mando", "dato"]', 0),

('ORG-4', 'area1', 'Reuniones y comunicación poco estructuradas', 'Las reuniones entre áreas son poco sistemáticas y muchas decisiones importantes se toman por correo, WhatsApp o conversaciones informales sin seguimiento.', 'medio', 'medio', '["No existe un calendario de reuniones operativas definido", "Ausencia de actas o acuerdos escritos y compartidos", "Uso intensivo de canales informales para decisiones críticas"]', '["Desalineación frecuente entre lo que se acordó y lo que se ejecuta", "Decisiones importantes que dependen de recordar conversaciones", "Reuniones que se convierten en discusiones circulares sin cierre claro"]', 'Diseñar un sistema mínimo de gobernanza: tipos de reuniones, frecuencia, asistentes, agenda y actas de acuerdos.', '["Definir tipos de reuniones (dirección, operativa, seguimiento de proyectos)", "Asignar periodicidad y responsables de convocatoria", "Implantar una plantilla simple de acta de reunión compartida", "Asegurar que las decisiones que afecten a procesos/datos se registran", "Revisar trimestralmente si las reuniones aportan valor o deben ajustarse"]', 1000, 3000, 80, 200, 'Ahorro de ~3-5h/semana en reuniones improductivas y repetición de información. Reducción de malentendidos que generan errores (~€200-400/mes). Mejor alineación reduce fricciones y urgencias.', '[]', '["comunicación interna", "reuniones", "gobernanza"]', 0),

('ORG-5', 'area1', 'Dependencia excesiva de perfiles técnicos para decisiones de negocio', 'Se espera que el perfil técnico (informático) defina o valide decisiones de negocio y de procesos que exceden su ámbito y requieren visión global de la empresa.', 'alto', 'corto', '["Confusión entre \\"gestionar tecnología\\" y \\"diseñar procesos de negocio\\"", "Ausencia de rol de consultoría interna o analista de procesos", "Histórico de delegar en informática todo aquello que toca un software"]', '["Expectativa de que el técnico asuma trazabilidad completa del dato", "Decisiones de proceso justificadas por \\"lo que dice el programa\\"", "Sobrecarga de tareas no técnicas en el perfil técnico"]', 'Separar claramente el rol de tecnología (soporte, sistemas) del rol de procesos/negocio, redefiniendo responsabilidades y expectativas.', '["Mapear tareas actuales del perfil técnico y clasificarlas (sistemas vs procesos)", "Definir qué tareas de negocio deben reasignarse a responsables de proceso", "Comunicar la nueva distribución de responsabilidades a toda la organización", "Acompañar al perfil técnico en la transición para centrarlo en su rol real", "Revisar tras 6 meses si la separación de funciones ha reducido fricciones"]', 2000, 5000, 100, 250, 'Liberación del 30-40% del tiempo del perfil técnico para tareas de su competencia real. Reducción de frustraciones y rotación (coste de sustitución ~€8.000-15.000). Mejor rendimiento de proyectos tecnológicos.', '["ORG-1", "ORG-2"]', '["roles", "tecnologia", "procesos"]', 0);

-- ===========================================
-- PROBLEMAS - ÁREA 2: ALMACÉN Y LOGÍSTICA
-- ===========================================
INSERT INTO problemas (id, area_id, titulo, descripcion, impacto, urgencia, causas, evidencias, solucion_propuesta, pasos_implementacion, coste_minimo, coste_maximo, roi_minimo, roi_maximo, roi_justificacion, dependencias, tags, is_custom) VALUES
('ALM-1', 'area2', 'Descuadre crónico entre stock físico y stock digital', 'Las existencias registradas en el sistema no coinciden de forma fiable con lo que realmente hay en los almacenes, lo que impide confiar en el dato para planificar.', 'alto', 'corto', '["Entradas y salidas sin registrar o registradas con retraso", "Procesos manuales y heterogéneos entre sedes", "Falta de ciclos de inventario y de responsables claros por zona"]', '["Imposibilidad de conocer el stock real disponible por referencia", "Necesidad de comprobaciones físicas constantes para servir pedidos", "Desajustes importantes detectados tras inventarios anuales"]', 'Diseñar e implantar un modelo de gestión de stock con ubicaciones, responsables por zona e inventarios cíclicos apoyados en el ERP.', '["Definir estructura de almacén (zonas, ubicaciones, referencias por zona)", "Asignar responsables de stock por área/ubicación", "Implantar inventarios cíclicos planificados por familias y zonas", "Ajustar procedimientos de entrada y salida para que sean obligatorios", "Medir y seguir mensualmente el nivel de ajuste stock físico/digital"]', 4000, 10000, 180, 450, 'Reducción del stock de seguridad innecesario (~10-15% del valor de inventario). Eliminación de roturas de stock y urgencias (~€500-1.500/mes). Ahorro en tiempo de comprobaciones físicas (~10h/semana).', '["ORG-1"]', '["stock", "inventario", "logística"]', 0),

('ALM-2', 'area2', 'Pedidos internos entre sedes sin circuito estándar', 'Los almacenes envían peticiones de material a la sede central mediante proformas, correos o documentos no integrados, perdiendo trazabilidad desde el origen.', 'alto', 'medio', '["Inexistencia de un flujo estándar de \\"pedido interno\\" en el sistema", "Histórico de usar formatos ofimáticos ad hoc", "Falta de formación y acompañamiento en el uso del ERP para estas funciones"]', '["Pedidos de almacenes introducidos como si fueran de Candelaria", "Pérdida de trazabilidad desde el almacén de origen hasta la producción", "Necesidad de llamadas y correos para confirmar estados de peticiones"]', 'Implantar un circuito formal de pedidos internos entre sedes dentro del ERP, con estados y responsabilidades claros.', '["Definir el flujo estándar de pedido interno (origen, revisión, preparación, envío, recepción)", "Parametrizar el ERP para soportar el circuito de pedidos internos", "Formar a los responsables de cada almacén en el nuevo flujo", "Cerrar progresivamente los canales paralelos (proformas, hojas sueltas)", "Revisar incidencias y ajustar el flujo tras los primeros meses"]', 2500, 6000, 120, 320, 'Ahorro de ~8-12h/semana en gestión manual de pedidos entre sedes. Reducción de errores en pedidos internos (~€300-600/mes). Mejor trazabilidad reduce pérdidas y reclamaciones internas.', '["ALM-1"]', '["pedidos internos", "multi-almacén", "trazabilidad"]', 0),

('ALM-3', 'area2', 'Falta de ubicaciones definidas y etiquetado sistemático', 'El material no está siempre asociado a una ubicación estructurada (pasillo/estantería/nivel), lo que dificulta localizar referencias de forma rápida y homogénea.', 'medio', 'medio', '["Almacenes creados y ampliados sin un plan de ubicaciones", "Ausencia de etiquetas normalizadas y criterios únicos de colocación", "Falta de integración entre ubicación física y registro digital"]', '["Dependencia del conocimiento de personas concretas para encontrar material", "Tiempos largos de preparación de pedidos en determinados almacenes", "Dificultad para implantar inventarios cíclicos por zonas"]', 'Diseñar un esquema de ubicaciones y etiquetado compatible con el ERP, empezando por las zonas de mayor rotación.', '["Analizar distribución actual y definir arquitectura de ubicaciones", "Diseñar sistema de codificación (ej. pasillo-estantería-nivel)", "Etiquetar físicamente ubicaciones y, cuando proceda, mercancías", "Vincular ubicaciones al maestro de artículos en el ERP", "Formar al personal de almacén e incluir ubicaciones en los documentos de trabajo"]', 3000, 7000, 100, 280, 'Reducción del tiempo de preparación de pedidos (~20-30%). Cualquier operario puede localizar material sin depender de expertos. Menos errores de picking (~€200-500/mes en devoluciones/correcciones).', '["ALM-1"]', '["ubicaciones", "etiquetado", "almacén"]', 0),

('ALM-4', 'area2', 'Uso intensivo de llamadas y WhatsApp para coordinar envíos', 'La coordinación diaria entre almacenes, producción y administración depende de llamadas, mensajes instantáneos y comunicaciones informales sin registro estructurado.', 'medio', 'corto', '["Carencia de herramientas sencillas para registrar y consultar estados", "Falta de confianza en el dato del sistema y en sus estados", "Necesidad de resolver urgencias en el día a día sin soporte digital"]', '["Cientos de llamadas mensuales para consultar estados de pedidos y stock", "Repetición de la misma información a distintas personas", "Imposibilidad de auditar a posteriori qué se acordó y cuándo"]', 'Reducir las dependencias de comunicación informal implantando estados visibles en el ERP y un panel mínimo de seguimiento operativo.', '["Definir un catálogo simple de estados de pedido y de movimientos de almacén", "Parametrizar el ERP para reflejar estos estados y hacerlos visibles", "Crear vistas/paneles donde los responsables puedan ver la carga y los estados sin llamar", "Establecer la regla de que primero se consulta el sistema y solo luego se llama si hay dudas", "Medir la reducción de llamadas tras la implantación"]', 2000, 5000, 150, 380, 'Reducción drástica de llamadas internas (~60-80%, estimado 200+ llamadas/mes). Ahorro de ~15-20h/semana en interrupciones. Personal puede consultar estados sin depender de otros, mejorando productividad general.', '["ALM-1", "ALM-2"]', '["comunicación", "operaciones", "paneles"]', 0),

('ALM-5', 'area2', 'Ausencia de indicadores logísticos (nivel de servicio, plazos, incidencias)', 'No se miden de forma sistemática los plazos de preparación, frecuencia de errores, retrasos o incidencias en almacén y logística.', 'medio', 'medio', '["No se han definido indicadores logísticos concretos", "Los datos necesarios no siempre se registran en el sistema", "La prioridad diaria es \\"sacar el trabajo\\" sin medir cómo"]', '["Dificultad para saber cuántos pedidos salen en plazo", "Imposibilidad de cuantificar errores de preparación o envíos incompletos", "Sensación generalizada de saturación sin métricas objetivas"]', 'Definir y poner en marcha un pequeño cuadro de mando logístico a partir de la información disponible en el ERP y/o herramientas complementarias.', '["Seleccionar 3–5 indicadores clave (plazo medio, pedidos en plazo, errores de preparación, etc.)", "Verificar qué datos existen en el ERP y qué hay que empezar a registrar", "Configurar informes o paneles automáticos mensuales", "Revisar los indicadores con responsables de almacén y producción", "Utilizar los datos para priorizar mejoras de proceso"]', 2000, 5000, 90, 220, 'Visibilidad sobre problemas permite actuar antes de perder clientes. Mejora del nivel de servicio retiene clientes (~€5.000-15.000/cliente/año). Datos objetivos para negociar con proveedores de transporte.', '["ALM-1", "ALM-2"]', '["kpi", "logística", "servicio"]', 0);

-- ===========================================
-- PROBLEMAS - ÁREA 3: ADMINISTRACIÓN
-- ===========================================
INSERT INTO problemas (id, area_id, titulo, descripcion, impacto, urgencia, causas, evidencias, solucion_propuesta, pasos_implementacion, coste_minimo, coste_maximo, roi_minimo, roi_maximo, roi_justificacion, dependencias, tags, is_custom) VALUES
('ADM-1', 'area3', 'Dispersión de herramientas contables y administrativas', 'Coexisten distintos programas y hojas auxiliares para facturación, contabilidad y reporting, lo que genera duplicidades, errores y falta de visión única.', 'alto', 'medio', '["Evolución histórica con soluciones parciales (LIBRA, TRIVALLE, hojas de cálculo)", "Diferente grado de confianza en cada herramienta según el usuario", "Ausencia de una hoja de ruta clara sobre qué sistema es el de referencia"]', '["Repetición de datos en varias herramientas", "Tareas manuales para cuadrar información entre sistemas", "Dudas recurrentes sobre qué cifra es la \\"buena\\" en cada informe"]', 'Definir un sistema contable y de facturación de referencia y una estrategia de transición clara para reducir herramientas y duplicidades.', '["Mapear qué procesos se hacen en cada herramienta actual", "Evaluar funcionalidad y costes de cada sistema frente a necesidades reales", "Tomar una decisión explícita sobre el sistema contable/facturación de referencia", "Definir un plan de transición por fases, priorizando la eliminación de duplicidades", "Formar al equipo en el sistema objetivo y acompañar durante la adaptación"]', 3500, 9000, 130, 350, 'Eliminación de duplicidades ahorra ~10-15h/semana. Un solo sistema de referencia reduce errores de cuadre (~€500-1.000/mes). Menor coste de mantenimiento de múltiples herramientas (~€2.000-4.000/año).', '["ORG-1"]', '["contabilidad", "facturación", "sistemas"]', 0),

('ADM-2', 'area3', 'Conciliaciones bancarias y gestión de cobros demasiado manuales', 'La conciliación de movimientos bancarios y la gestión de cobros requiere muchas horas de trabajo manual y controles adicionales.', 'medio', 'medio', '["No se aprovechan funcionalidades de conciliación automática del ERP", "Dificultad de integración directa con bancos", "Procesos diseñados históricamente alrededor del papel y listados impresos"]', '["Muchas horas mensuales dedicadas a conciliar bancos", "Revisión manual de movimientos y asignación a facturas", "Riesgo de errores en la aplicación de cobros y saldos abiertos"]', 'Introducir conciliación semiautomática o automática con ficheros bancarios e integrar, cuando sea viable, los bancos con el ERP.', '["Revisar qué opciones de conciliación ofrece el sistema contable elegido", "Configurar la importación de movimientos bancarios (ficheros norma 43 u otros)", "Definir reglas de conciliación automática por patrón de conceptos e importes", "Formar al equipo para validar y revisar las conciliaciones sugeridas por el sistema", "Medir la reducción de tiempo dedicado a esta tarea"]', 2000, 5000, 150, 400, 'La conciliación automática reduce el tiempo de ~20h/mes a ~3-4h/mes. Menos errores de aplicación de cobros (~€300-600/mes en incidencias). Personal administrativo liberado para tareas de mayor valor.', '["ADM-1"]', '["conciliación", "banca", "automatización"]', 0),

('ADM-3', 'area3', 'Carga administrativa elevada por falta de automatización documental', 'Gran parte del tiempo administrativo se consume en introducir datos de facturas, buscar documentos y completar tareas mecánicas.', 'medio', 'medio', '["Digitalización de facturas y documentos poco sistemática", "No se utiliza OCR de forma integrada", "Ausencia de flujos automáticos de aprobación o clasificación"]', '["Tiempo significativo dedicado a registrar facturas de proveedores", "Búsquedas manuales frecuentes de documentos para aclarar incidencias", "Sensación de \\"papel digital\\" en lugar de procesos digitalizados"]', 'Introducir un flujo de captura y clasificación automática de documentos (OCR) integrado con el sistema contable y de gestión.', '["Seleccionar una solución OCR adecuada al volumen de facturas", "Definir el flujo de trabajo: recepción, escaneo, validación, contabilización", "Integrar el OCR con el sistema contable/ERP", "Formar al personal administrativo en el nuevo flujo", "Medir tiempos antes y después para validar el ahorro real"]', 3000, 8000, 120, 300, 'OCR reduce tiempo de entrada de facturas de proveedores ~70-80% (~15-25h/mes). Menor tasa de errores de transcripción. Búsqueda de documentos instantánea vs. archivos físicos (~5h/mes ahorradas).', '["ADM-1"]', '["ocr", "documentos", "automatización"]', 0),

('ADM-4', 'area3', 'Reporting financiero poco orientado a la operación', 'La información financiera se centra en cierres y obligaciones legales, pero no se orienta de manera sistemática a la toma de decisiones operativas y comerciales.', 'medio', 'largo', '["Prioridad en cumplimiento fiscal frente a visión de gestión", "Falta de conexión entre contabilidad analítica y la operativa diaria", "Limitaciones de los informes estándar del sistema actual"]', '["Dificultad para obtener información por línea de negocio, sede o familia", "Escaso uso de la contabilidad analítica para decisiones de precios o clientes", "Necesidad de exportar datos a Excel para hacer análisis ad hoc"]', 'Rediseñar el reporting financiero desde una lógica de gestión, conectándolo con operaciones, ventas y producción.', '["Definir, con Dirección, qué preguntas de negocio debe responder la información financiera", "Ajustar el plan contable y la analítica a esa estructura", "Configurar informes estándar o cuadros de mando financieros", "Formar a mandos intermedios en la interpretación de estos informes", "Revisar cada trimestre si la información responde a las necesidades reales"]', 2500, 6000, 80, 220, 'Información financiera orientada a gestión permite identificar líneas/clientes no rentables (~1-2% de mejora de margen). Reducción de tiempo en preparar informes ad hoc (~8-10h/mes).', '["ORG-3", "ADM-1"]', '["reporting", "finanzas", "gestión"]', 0),

('ADM-5', 'area3', 'Uso limitado de la información administrativa para detectar fugas de margen', 'Aunque se dispone de mucha información de compras y ventas, no se explota sistemáticamente para detectar clientes, productos o líneas con baja rentabilidad.', 'medio', 'medio', '["Datos dispersos en varios sistemas", "Falta de visión integrada coste–precio–desperdicio", "Escasez de herramientas de análisis orientadas a negocio"]', '["Desconocimiento del margen real por producto o cliente", "Dificultad para priorizar subidas de precio o renegociaciones", "Poca visibilidad sobre el impacto económico del desperdicio"]', 'Construir una visión simplificada de margen por línea y cliente, usando la información disponible y completándola allí donde sea necesario.', '["Identificar qué datos de coste y precio están disponibles por referencia", "Definir un modelo simple de cálculo de margen por producto/cliente", "Montar un primer informe o dashboard de margen", "Validar los resultados con administración y dirección", "Usar estos datos como base para decisiones comerciales y de precios"]', 2500, 6000, 200, 500, 'Detectar fugas de margen del 2-5% en líneas o clientes concretos representa €40.000-100.000/año en una empresa de este tamaño. Permite renegociar precios o eliminar productos/clientes no rentables.', '["ADM-1", "ADM-4"]', '["margen", "análisis", "rentabilidad"]', 0);

-- ===========================================
-- PROBLEMAS - ÁREA 4: VENTAS
-- ===========================================
INSERT INTO problemas (id, area_id, titulo, descripcion, impacto, urgencia, causas, evidencias, solucion_propuesta, pasos_implementacion, coste_minimo, coste_maximo, roi_minimo, roi_maximo, roi_justificacion, dependencias, tags, is_custom) VALUES
('VEN-1', 'area4', 'Ausencia de CRM para gestión de clientes y oportunidades', 'La relación con clientes se gestiona principalmente a través de correo, teléfono y conocimiento individual, sin una herramienta centralizada de seguimiento.', 'alto', 'medio', '["Enfoque tradicional basado en relaciones personales", "No se ha priorizado la implantación de un CRM", "Miedo a añadir carga administrativa al equipo comercial"]', '["No hay listado único y actualizado de oportunidades abiertas", "Dificultad para saber qué clientes están en riesgo de fuga", "Pérdida de histórico cuando cambia una persona del equipo"]', 'Implantar un CRM ligero integrado con el flujo de pedidos y comunicaciones básicas.', '["Seleccionar una herramienta CRM adaptada al tamaño y necesidades reales", "Definir campos mínimos y etapas del embudo comercial", "Cargar la base activa de clientes y principales contactos", "Formar al equipo comercial y administración en su uso diario", "Conectar el CRM, cuando sea posible, con el sistema de pedidos"]', 3000, 8000, 150, 400, 'Un CRM evita perder oportunidades (~5-10% más conversión). Retener 2-3 clientes/año que se habrían perdido representa €15.000-50.000. Ahorro de tiempo comercial en buscar información (~5h/semana).', '["ORG-3"]', '["crm", "clientes", "ventas"]', 0),

('VEN-2', 'area4', 'Gestión reactiva de incidencias comerciales y de servicio', 'Las incidencias de clientes (retrasos, errores de preparación, problemas de calidad) se gestionan caso a caso sin un registro sistemático ni análisis posterior.', 'medio', 'medio', '["No existe un registro estructurado de incidencias comerciales", "Falta de responsables claros de seguimiento por tipo de incidencia", "Ausencia de indicadores de calidad de servicio por cliente o línea"]', '["Repetición de problemas con algunos clientes sin visibilidad agregada", "Imposibilidad de saber cuántas incidencias se producen al mes", "Gestión de quejas muy dependiente de la buena voluntad de las personas"]', 'Crear un circuito simple de registro y seguimiento de incidencias comerciales, enlazado a clientes y pedidos.', '["Definir tipos de incidencias y niveles de gravedad", "Diseñar un formulario mínimo de registro (en CRM o herramienta compartida)", "Asignar responsables de resolución y plazos máximos", "Revisar mensualmente incidencias abiertas/cerradas y causas raíz", "Priorizar mejoras de proceso donde más se repiten incidencias"]', 1500, 4000, 100, 280, 'Gestión estructurada de incidencias reduce tiempo de resolución (~40%). Identificar causas raíz evita repetición (~€400-800/mes en costes de re-envíos, descuentos, etc.). Mejora satisfacción cliente.', '["VEN-1"]', '["incidencias", "servicio", "clientes"]', 0),

('VEN-3', 'area4', 'Escasa visibilidad sobre pérdida de clientes y motivos', 'No se dispone de datos estructurados que indiquen qué clientes han reducido o dejado de comprar, ni por qué.', 'alto', 'medio', '["No se analizan patrones de compra por cliente de forma periódica", "No hay procesos de \\"post mortem\\" cuando se pierde un cliente", "Limitaciones de los sistemas actuales para segmentar ventas por cliente"]', '["Percepción de pérdida o estancamiento de ventas sin detalle por cliente", "Ausencia de indicadores de retención o abandono", "Dificultad para separar \\"menos demanda\\" de \\"cliente fugado\\""]', 'Analizar ventas históricas por cliente y crear un panel de actividad que marque clientes en riesgo de fuga.', '["Exportar y consolidar datos de ventas por cliente de los últimos 12–24 meses", "Definir qué se considera cliente \\"activo\\", \\"en riesgo\\" y \\"perdido\\"", "Configurar un informe periódico que identifique cambios significativos", "Implantar un protocolo de contacto cuando un cliente entre en riesgo", "Medir recuperación o pérdida definitiva tras estas acciones"]', 2000, 5000, 200, 600, 'Captar un cliente nuevo cuesta 5-7x más que retener uno existente. Detectar y recuperar 3-5 clientes en riesgo/año representa €30.000-80.000 en facturación salvada. El coste de análisis es mínimo.', '["ADM-5", "VEN-1"]', '["fuga de clientes", "análisis", "ventas"]', 0),

('VEN-4', 'area4', 'Canales de comunicación con clientes poco estructurados', 'Las peticiones de clientes llegan por múltiples canales (teléfono, correo, WhatsApp) sin una entrada única ni prioridad clara.', 'medio', 'corto', '["No existe una bandeja de entrada común para solicitudes comerciales", "Cada persona gestiona sus propios correos y mensajes", "No se ha definido un SLA de respuesta"]', '["Llamadas perdidas o correos no respondidos a tiempo", "Sensación en el equipo de \\"ir siempre apagando fuegos\\"", "Clientes que vuelven a llamar porque no obtienen respuesta"]', 'Centralizar la entrada de solicitudes comerciales en una herramienta o buzón compartido, con criterios de reparto y prioridad.', '["Crear una dirección de correo o canal común para peticiones de clientes", "Definir reglas de asignación y tiempos de respuesta estándar", "Configurar alertas o paneles de solicitudes pendientes", "Formar al equipo en el uso del nuevo canal y apagar canales alternativos de forma gradual", "Revisar mensualmente tiempos de respuesta y volumen de solicitudes"]', 1000, 3000, 80, 200, 'Centralizar comunicaciones reduce tiempo de respuesta (~50%), mejorando satisfacción. Evita pérdida de pedidos por mensajes no atendidos (~€500-1.500/mes). Libera tiempo comercial para vender, no para buscar información.', '[]', '["comunicación", "clientes", "operación comercial"]', 0),

('VEN-5', 'area4', 'Poca conexión entre información comercial y capacidad productiva', 'Las decisiones comerciales (plazos, compromisos, ofertas) no siempre se basan en información actualizada de carga de producción y disponibilidad real.', 'medio', 'medio', '["Falta de visibilidad compartida sobre carga de planta y colas", "No existen alertas cuando se comprometen plazos difíciles de cumplir", "Desconexión entre los sistemas de pedidos y la planificación"]', '["Promesa de plazos que luego son difíciles de cumplir", "Tensiones entre comercial y producción en momentos de carga alta", "Ajustes de última hora que penalizan organización interna"]', 'Crear un mecanismo mínimo de visibilidad de capacidad y carga que pueda ser consultado por el área comercial al comprometer plazos.', '["Definir indicadores simples de carga (por máquina, por semana, por línea)", "Configurar vistas en el ERP o herramienta auxiliar para ver carga actual y comprometida", "Formar al equipo comercial para consultar esta información antes de prometer fechas", "Revisar semanalmente desviaciones entre plazos prometidos y reales", "Ajustar reglas de compromiso de plazo en función de los datos"]', 2500, 6000, 120, 320, 'Evitar compromisos de plazo imposibles reduce tensiones y horas extra (~€800-1.500/mes). Menos incumplimientos mejora satisfacción cliente y reduce penalizaciones/descuentos (~€300-600/mes).', '["PRO-1"]', '["planificación", "comercial", "capacidad"]', 0);

-- ===========================================
-- PROBLEMAS - ÁREA 5: PRODUCCIÓN
-- ===========================================
INSERT INTO problemas (id, area_id, titulo, descripcion, impacto, urgencia, causas, evidencias, solucion_propuesta, pasos_implementacion, coste_minimo, coste_maximo, roi_minimo, roi_maximo, roi_justificacion, dependencias, tags, is_custom) VALUES
('PRO-1', 'area5', 'Ausencia de planificación formal de producción (MRP/MPS)', 'La carga de producción se organiza de forma muy manual y reactiva, con poca ayuda estructurada del sistema para secuenciar trabajos y asignar recursos.', 'alto', 'medio', '["No se ha configurado o aprovechado un módulo de planificación en el ERP", "La experiencia de las personas suple la falta de herramienta", "Cambios constantes de prioridad sin un sistema que los gestione"]', '["Dificultad para anticipar carga y cuellos de botella", "Reprogramaciones frecuentes y urgencias diarias", "Escaso control sobre el impacto de cambios de última hora"]', 'Implantar una planificación básica de producción apoyada en el ERP o en una herramienta especializada integrada.', '["Definir reglas básicas de secuenciación (por tipo de perfil, aleación, plazo, etc.)", "Configurar el módulo de planificación existente o seleccionar uno nuevo", "Formar a la figura de Regulador en el uso de la herramienta", "Establecer una rutina diaria de planificación y revisión", "Analizar indicadores de cumplimiento de plan y ajustar reglas"]', 5000, 12000, 180, 500, 'Planificación formal reduce tiempos muertos de máquina (~10-15%), horas extra por urgencias (~€1.500-3.000/mes) y mejora OEE general. En producción de extrusión, 1% de mejora de eficiencia puede representar €20.000-40.000/año.', '["ALM-1"]', '["planificación", "producción", "mrp"]', 0),

('PRO-2', 'area5', 'Datos de producción sin objetivo ni explotación real', 'Se introducen datos en fases intermedias sin un plan claro sobre cómo se van a utilizar para medir rendimiento, desperdicio o trazabilidad.', 'alto', 'corto', '["Implantación de fases en el ERP sin diseño de indicadores previos", "Ausencia de cuadro de mando de producción", "Falta de acompañamiento para transformar datos en decisiones"]', '["Horas dedicadas a introducir datos que no retornan información útil", "No hay indicadores consolidados de eficiencia por máquina o línea", "Gestores que desconocen el destino y utilidad de los datos que piden"]', 'Redefinir las capturas de datos de planta partiendo de los indicadores que se quieren obtener, no al revés.', '["Definir junto a planta qué indicadores son prioritarios (rendimiento, desperdicio, OEE simplificado, etc.)", "Analizar qué datos son imprescindibles para esos indicadores", "Rediseñar las pantallas o registros de captura de datos", "Eliminar capturas que no aportan valor y generan carga", "Construir informes claros que devuelvan información útil de esos datos"]', 3000, 8000, 150, 400, 'Datos útiles permiten identificar cuellos de botella y pérdidas ocultas. Eliminar capturas innecesarias ahorra ~5-8h/semana. Indicadores claros motivan mejoras que pueden representar 2-3% de productividad (~€15.000-30.000/año).', '["ORG-3"]', '["datos de planta", "indicadores", "eficiencia"]', 0),

('PRO-3', 'area5', 'Falta de control estructurado del desperdicio en extrusión', 'Aunque teóricamente se puede calcular el desperdicio como diferencia entre kg de entrada y salida por matriz, esto no se hace de manera consistente ni se integra en la gestión diaria.', 'alto', 'medio', '["No existe una tabla consolidada y operativa de desperdicio por matriz", "El ERP no se explota para integrar estos datos en los informes de gestión", "Estos datos no se vinculan a decisiones de mejora o mantenimiento"]', '["Imposibilidad actual de conocer el desperdicio real por producto o matriz", "Falta de objetivos de mejora ligados a indicadores de desperdicio", "Percepción de que se pierde dinero sin cuantificación exacta"]', 'Construir un sistema sencillo y fiable de registro y análisis de desperdicio por matriz y periodo.', '["Definir claramente el modelo de datos de desperdicio (entradas, salidas, matriz, fecha, máquina)", "Determinar si se captura en el ERP actual o en una tabla externa integrada", "Establecer la rutina de registro por turno o por orden de fabricación", "Configurar informes que muestren desperdicio por matriz, máquina y periodo", "Ligar estos datos a decisiones de mantenimiento, ajustes de proceso o formación"]', 3000, 7000, 250, 800, 'El desperdicio en extrusión puede representar 3-8% del aluminio procesado. Controlarlo y reducirlo un 1-2% en una planta que procesa 500-1.000 toneladas/año representa €25.000-80.000/año de ahorro directo en materia prima.', '["PRO-2"]', '["desperdicio", "extrusión", "costes"]', 0),

('PRO-4', 'area5', 'Trazabilidad incompleta de pedidos a lo largo del flujo productivo', 'No se puede seguir fácilmente el estado de un pedido desde la recepción hasta la expedición utilizando únicamente el sistema.', 'alto', 'medio', '["Fases de producción configuradas sin conexión práctica con el flujo de pedidos", "Falta de disciplina a la hora de actualizar estados", "Uso de comunicaciones paralelas (boca-oreja, listas de papel, llamadas)"]', '["Necesidad de preguntar físicamente en planta por el estado de un pedido", "Descoordinación entre lo que producción considera terminado y lo que administración sabe", "Clientes que preguntan por pedidos y no obtienen respuesta inmediata fiable"]', 'Diseñar un flujo mínimo de estados de pedido enlazado a hitos reales de producción y registro en el sistema.', '["Definir estados clave del pedido (ej. en cola, en fabricación, en anodizado, listo para expedición, enviado)", "Mapear estos estados con las etapas reales de producción", "Configurar el ERP para reflejar estos estados y quién los actualiza", "Formar al personal en el uso de estos estados como parte del trabajo", "Crear vistas para que administración y comercial puedan consultar el estado sin llamar"]', 4000, 10000, 120, 350, 'Trazabilidad completa reduce tiempo de consultas (~10-15h/semana). Clientes pueden ser informados sin llamadas internas. Menos errores de expedición (~€400-800/mes). Mejor imagen ante clientes exigentes.', '["ALM-2", "ALM-4", "PRO-1"]', '["trazabilidad", "pedidos", "producción"]', 0),

('PRO-5', 'area5', 'Dependencia excesiva de la figura del Regulador para priorizar y coordinar', 'La persona que regula la producción asume una carga muy alta de llamadas, decisiones y coordinación manual, con poco apoyo estructurado del sistema.', 'medio', 'corto', '["Falta de paneles visuales de carga y estados", "Ausencia de criterios objetivos compartidos para priorizar", "Insuficiente distribución de responsabilidad en el equipo"]', '["Elevado número de llamadas diarias hacia el regulador", "Baja posibilidad de delegar si esa persona no está", "Dificultad para explicar por qué se priorizaron unos trabajos frente a otros"]', 'Dotar al Regulador de herramientas visuales de planificación y estados, y definir reglas de prioridad compartidas.', '["Identificar la información mínima que el Regulador necesita ver en tiempo real", "Configurar un panel de trabajo (en ERP o herramienta auxiliar) con esa información", "Definir reglas de prioridad y documentarlas para todo el equipo", "Formar a otros perfiles para que puedan asumir parte de la regulación si es necesario", "Medir reducción de llamadas e incidencias en el área tras los cambios"]', 3000, 7000, 130, 350, 'Reducir dependencia del regulador disminuye riesgo operativo (€15.000-25.000 si hay baja prolongada). Herramientas visuales reducen llamadas (~50-70%) y permiten delegar decisiones. Reglas claras reducen conflictos.', '["PRO-1", "ALM-4"]', '["regulación", "carga de trabajo", "paneles"]', 0);

-- ===========================================
-- PROBLEMAS - ÁREA 6: DIRECCIÓN
-- ===========================================
INSERT INTO problemas (id, area_id, titulo, descripcion, impacto, urgencia, causas, evidencias, solucion_propuesta, pasos_implementacion, coste_minimo, coste_maximo, roi_minimo, roi_maximo, roi_justificacion, dependencias, tags, is_custom) VALUES
('DIR-1', 'area6', 'Inversiones tecnológicas sin cálculo formal de retorno (ROI)', 'Las decisiones de inversión en software y servicios tecnológicos se han tomado históricamente sin un análisis estructurado de retorno de inversión.', 'alto', 'medio', '["Falta de metodología de evaluación económica específica para tecnología", "Presión de urgencias operativas y normativas", "Historial de proyectos donde el beneficio esperado no se ha hecho explícito"]', '["Dificultad para defender nuevas inversiones frente a la propiedad", "Percepción de \\"mucho dinero gastado\\" sin resultados claros", "Ausencia de comparativas antes/después por proyecto tecnológico"]', 'Implantar una metodología simple de análisis de ROI tecnológico para cualquier proyecto relevante.', '["Definir plantilla estándar de caso de negocio para proyectos de tecnología", "Incluir siempre estimación de ahorro de horas, reducción de errores y mejora de servicio", "Hacer seguimiento anual del ROI real de los proyectos aprobados", "Usar estos datos para priorizar futuras inversiones", "Compartir con la propiedad resultados de forma clara y transparente"]', 2000, 5000, 150, 400, 'Metodología de ROI evita inversiones fallidas (~€10.000-30.000/año en proyectos que no aportan). Permite priorizar inversiones con mayor retorno. Facilita comunicación con propiedad y justificación de gastos.', '["ORG-3"]', '["roi", "inversión", "estrategia"]', 0),

('DIR-2', 'area6', 'Falta de hoja de ruta tecnológica alineada con la estrategia de negocio', 'No existe un plan a 2–3 años que marque qué sistemas se van a mantener, sustituir o reforzar y en qué orden.', 'alto', 'medio', '["Enfoque reactivo frente a problemas inmediatos", "Incógnitas sobre la situación actual real de los sistemas", "Escasez de tiempo para pensar en clave de medio plazo"]', '["Dudas recurrentes sobre seguir o no con determinados proveedores", "Multiplicidad de propuestas y ofertas sin un marco de decisión claro", "Sensación de estar \\"atado\\" a decisiones del pasado"]', 'Construir una hoja de ruta tecnológica realista que priorice pocas decisiones clave y las conecte con objetivos de negocio.', '["Tomar como base el diagnóstico actual de sistemas y procesos", "Identificar 3–5 decisiones críticas (ERP, CRM, BI, automatización, etc.)", "Ordenarlas por impacto y viabilidad económica", "Asignar horizontes temporales y criterios de éxito por hito", "Revisar la hoja de ruta cada 6 meses en función de la realidad"]', 3000, 8000, 120, 350, 'Una hoja de ruta clara evita cambios de rumbo costosos (~€5.000-15.000/año). Permite negociar mejor con proveedores tecnológicos. Reduce ansiedad organizacional y mejora adopción de cambios.', '["DIR-1", "ORG-1"]', '["roadmap", "tecnología", "priorización"]', 0),

('DIR-3', 'area6', 'Gobierno de proyectos de mejora poco definido', 'Los proyectos de mejora (tecnológicos y organizativos) no siempre tienen un patrocinador claro, un alcance definido ni una estructura de seguimiento.', 'medio', 'medio', '["Carencia de metodología de gestión de proyectos adaptada a la empresa", "Asunción informal de responsabilidades por parte de personas concretas", "Limitaciones de tiempo de la Dirección para seguimiento detallado"]', '["Proyectos que se alargan más de lo previsto sin explicación clara", "Cambios de alcance sobre la marcha", "Iniciativas que se quedan a medias o no se consolidan"]', 'Introducir una forma ligera de gestión de proyectos con roles básicos, hitos y revisiones periódicas.', '["Definir qué se considera proyecto y qué no", "Asignar siempre un patrocinador, un responsable operativo y un equipo", "Usar una plantilla estándar de plan de proyecto con hitos y fechas", "Revisar proyectos activos mensualmente en un foro específico", "Cerrar formalmente los proyectos, recogiendo lecciones aprendidas"]', 2000, 5000, 100, 280, 'Proyectos bien gestionados terminan en plazo y presupuesto (~30% menos desviaciones). Evita proyectos zombi que consumen recursos sin cerrar. Lecciones aprendidas mejoran proyectos futuros.', '["DIR-1", "DIR-2"]', '["proyectos", "gobernanza", "mejora continua"]', 0),

('DIR-4', 'area6', 'Dependencia elevada de personas concretas para el funcionamiento global', 'Algunos puestos acumulan decisiones y conocimiento clave, de forma que su ausencia genera riesgo operativo importante.', 'alto', 'medio', '["No se han definido siempre puestos sino personas", "Poca rotación o backup planificado de funciones críticas", "Conocimiento no documentado y poco compartido"]', '["Preocupación cuando determinadas personas no están presentes", "Dificultad para delegar o escalar responsabilidades", "Sensación de \\"insustituibilidad\\" de algunos perfiles"]', 'Reducir la dependencia de personas individuales documentando procesos y definiendo suplencias y backups.', '["Identificar roles críticos y tareas que dependen de una sola persona", "Documentar procesos clave asociados a esos roles", "Definir personas de backup y darles tiempo para formarse", "Introducir rotaciones puntuales en tareas clave para compartir conocimiento", "Incorporar este enfoque en la estrategia de personas de la empresa"]', 2500, 6000, 120, 320, 'Reducir dependencia de personas clave mitiga riesgo operativo (coste potencial de baja prolongada: €20.000-50.000). Backups formados permiten vacaciones sin estrés. Conocimiento distribuido acelera resolución de problemas.', '["ORG-2"]', '["personas clave", "riesgo operativo", "conocimiento"]', 0),

('DIR-5', 'area6', 'Cultura de "siempre se ha trabajado así" que frena cambios', 'Existe resistencia natural al cambio en algunos niveles, lo que dificulta aprovechar plenamente las mejoras tecnológicas y de proceso.', 'medio', 'largo', '["Histórico de intentos de mejora que no han llegado a buen puerto", "Falta de comunicación clara sobre el porqué de los cambios", "Temor a que la tecnología sirva solo para controlar o recortar"]', '["Comentarios recurrentes del tipo \\"antes funcionaba\\" o \\"siempre se ha hecho así\\"", "Reticencia a registrar datos nuevos o seguir procedimientos modificados", "Percepción de la tecnología como imposición externa"]', 'Acompañar los cambios con comunicación honesta, participación de las personas afectadas y victorias tempranas visibles.', '["Involucrar a personas clave en el diseño de nuevas formas de trabajar", "Explicar con claridad los beneficios esperados para la empresa y para cada rol", "Planificar pilotos acotados con equipos concretos antes de escalar", "Reconocer públicamente los avances y las mejoras conseguidas", "Recoger feedback y ajustar sin perder el rumbo general"]', 1500, 4000, 80, 200, 'Gestión del cambio bien hecha aumenta adopción de mejoras (~50% más éxito en proyectos). Reduce resistencias que alargan implantaciones. Mejora clima laboral y retención de talento (~€5.000-10.000/año en rotación evitada).', '["DIR-2", "ORG-4"]', '["cultura", "cambio", "personas"]', 0);

-- ===========================================
-- FIN DE DATOS INICIALES
-- ===========================================



